### ISSUE TITLE
detail about transferring GTA5 dataset to Cityscapes photo style

### ISSUE THREAD

**Issue by chentao2016** [xiaosean/Gated-AdaptSegNet#2]
Thanks for your code!
Using FastPhotoStyle to transfer GTA5 dataset to Cityscapes photo style is a great obstacle for me to reproduce your results. I am wondering whether you can share your code about that part since I need more details like image size or whether using segmentation masks. Of course, if the transferred GTA5 images could be shared, I can skip that step can run your code directly.

**Comment by xiaosean** [comment]
Sorry for the late reply.
You can follow this code.
https://github.com/xiaosean/FastPhotoStyle/blob/master/transfer_GTA5_to_City_dataset.ipynb
