### ISSUE TITLE
code of FastPhotoStyle that transfer the style of Cityscapes to GTA5

### ISSUE THREAD

**Issue by Lufei-github** [xiaosean/Gated-AdaptSegNet#3]
Could you please provide the code of transfer the style Cityscapes to GTA5？Thanks very much！very much！very very much！!！

**Comment by xiaosean** [comment]
You can follow this code.
https://github.com/xiaosean/FastPhotoStyle/blob/master/transfer_GTA5_to_City_dataset.ipynb
